import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body >
        <header className="py-8 px-4 text-lg font-bold text-center border-b-2 border-b-cyan-600" >
          <h1>Header of Web App</h1>
        </header>
        {children}
        <footer className="py-8 px-4 text-lg font-bold text-center border-t-2 border-t-cyan-600" >
          <h1>Footer Of Web App</h1>
        </footer>
        </body>
    </html>
  );
}
