import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function ProductsLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <>
            {children}
            <footer className="py-8 px-4 text-lg font-bold text-center border-t-2 border-t-cyan-600" >
                <h1>Feature Products : </h1>
            </footer>
        </>
    );
}
